#
# Copyright(c) 2012-2013 ACCESS CO., LTD. All rights reserved.
#

# !BEGIN SECRET!
<%
  branch = (`git rev-parse --abbrev-ref HEAD` rescue '').chomp
  branch = ''           if branch == 'master'
  branch = '.' + branch if branch.size > 0
%>

sqlite_base: &sqlite_base
  adapter: sqlite3
  pool: 5
  timeout: 5000

# test:
#   <<: *sqlite_base
#   database: db/test.sqlite3

# test_log:
#   <<: *sqlite_base
#   database: db/test_log.sqlite3

# !END SECRET!

postgres_base: &postgres_base
  adapter: postgresql
  username: mayur
  password: welcome
  encoding: utf8
  pool: 5
  port: 5432

development:
  primary:
    <<: *postgres_base
    database: WeatherApp
    password: welcome
    host: localhost
  logs:
    <<: *postgres_base
    database: WeatherApp
    password: welcome
    host: localhost
    migrations_paths: db/log_migration


development_log:
  <<: *postgres_base
  database: WeatherApp
  host: localhost

production:
  <<: *postgres_base
  database: WeatherApp
  host: localhost

production_log:
  <<: *postgres_base
  database: WeatherApp
  host: localhost